# coding: utf-8

"""
    ConfigurationService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.rist_caller import RistCaller
from openapi_client.models.rist_listener import RistListener
from openapi_client.models.srt_caller import SrtCaller
from openapi_client.models.srt_listener import SrtListener
from openapi_client.models.zixi_caller import ZixiCaller
from openapi_client.models.zixi_listener import ZixiListener
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

TRANSPORTPROTOCOL_ONE_OF_SCHEMAS = ["RistCaller", "RistListener", "SrtCaller", "SrtListener", "ZixiCaller", "ZixiListener"]

class TransportProtocol(BaseModel):
    """
    TransportProtocol
    """
    # data type: SrtListener
    oneof_schema_1_validator: Optional[SrtListener] = None
    # data type: SrtCaller
    oneof_schema_2_validator: Optional[SrtCaller] = None
    # data type: RistListener
    oneof_schema_3_validator: Optional[RistListener] = None
    # data type: RistCaller
    oneof_schema_4_validator: Optional[RistCaller] = None
    # data type: ZixiListener
    oneof_schema_5_validator: Optional[ZixiListener] = None
    # data type: ZixiCaller
    oneof_schema_6_validator: Optional[ZixiCaller] = None
    actual_instance: Optional[Union[RistCaller, RistListener, SrtCaller, SrtListener, ZixiCaller, ZixiListener]] = None
    one_of_schemas: Set[str] = { "RistCaller", "RistListener", "SrtCaller", "SrtListener", "ZixiCaller", "ZixiListener" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = TransportProtocol.model_construct()
        error_messages = []
        match = 0
        # validate data type: SrtListener
        if not isinstance(v, SrtListener):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SrtListener`")
        else:
            match += 1
        # validate data type: SrtCaller
        if not isinstance(v, SrtCaller):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SrtCaller`")
        else:
            match += 1
        # validate data type: RistListener
        if not isinstance(v, RistListener):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RistListener`")
        else:
            match += 1
        # validate data type: RistCaller
        if not isinstance(v, RistCaller):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RistCaller`")
        else:
            match += 1
        # validate data type: ZixiListener
        if not isinstance(v, ZixiListener):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ZixiListener`")
        else:
            match += 1
        # validate data type: ZixiCaller
        if not isinstance(v, ZixiCaller):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ZixiCaller`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in TransportProtocol with oneOf schemas: RistCaller, RistListener, SrtCaller, SrtListener, ZixiCaller, ZixiListener. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in TransportProtocol with oneOf schemas: RistCaller, RistListener, SrtCaller, SrtListener, ZixiCaller, ZixiListener. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into SrtListener
        try:
            instance.actual_instance = SrtListener.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SrtCaller
        try:
            instance.actual_instance = SrtCaller.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RistListener
        try:
            instance.actual_instance = RistListener.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RistCaller
        try:
            instance.actual_instance = RistCaller.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ZixiListener
        try:
            instance.actual_instance = ZixiListener.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ZixiCaller
        try:
            instance.actual_instance = ZixiCaller.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into TransportProtocol with oneOf schemas: RistCaller, RistListener, SrtCaller, SrtListener, ZixiCaller, ZixiListener. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into TransportProtocol with oneOf schemas: RistCaller, RistListener, SrtCaller, SrtListener, ZixiCaller, ZixiListener. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], RistCaller, RistListener, SrtCaller, SrtListener, ZixiCaller, ZixiListener]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


