# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.range_values import RangeValues

class TestRangeValues(unittest.TestCase):
    """RangeValues unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RangeValues:
        """Test RangeValues
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RangeValues`
        """
        model = RangeValues()
        if include_optional:
            return RangeValues(
                min = 1.337,
                max = 1.337,
                default_value = 1.337
            )
        else:
            return RangeValues(
                min = 1.337,
                max = 1.337,
                default_value = 1.337,
        )
        """

    def testRangeValues(self):
        """Test RangeValues"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
