# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.channel import Channel

class TestChannel(unittest.TestCase):
    """Channel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Channel:
        """Test Channel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Channel`
        """
        model = Channel()
        if include_optional:
            return Channel(
                name = '',
                id = '',
                channel_type = 'SOURCE',
                settings = [
                    openapi_client.models.setting.Setting(
                        id = '', 
                        name = '', 
                        info = '', 
                        enums = openapi_client.models.enum_values.EnumValues(
                            values = [
                                ''
                                ], 
                            default_value = '', ), 
                        ranges = openapi_client.models.range_values.RangeValues(
                            min = 1.337, 
                            max = 1.337, 
                            default_value = 1.337, ), )
                    ],
                setting_profiles = [
                    openapi_client.models.profile.Profile(
                        name = '', 
                        id = '', 
                        info = '', )
                    ],
                connection_protocols = [
                    'srt_listener'
                    ]
            )
        else:
            return Channel(
                name = '',
                id = '',
        )
        """

    def testChannel(self):
        """Test Channel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
