# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.report_status_request_content import ReportStatusRequestContent

class TestReportStatusRequestContent(unittest.TestCase):
    """ReportStatusRequestContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportStatusRequestContent:
        """Test ReportStatusRequestContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportStatusRequestContent`
        """
        model = ReportStatusRequestContent()
        if include_optional:
            return ReportStatusRequestContent(
                status = openapi_client.models.device_status.DeviceStatus(
                    channels = [
                        openapi_client.models.channel_status.ChannelStatus(
                            id = '', 
                            state = 'ACTIVE', 
                            status = [
                                openapi_client.models.status_value.StatusValue(
                                    name = '', 
                                    info = '', 
                                    value = '', )
                                ], )
                        ], )
            )
        else:
            return ReportStatusRequestContent(
                status = openapi_client.models.device_status.DeviceStatus(
                    channels = [
                        openapi_client.models.channel_status.ChannelStatus(
                            id = '', 
                            state = 'ACTIVE', 
                            status = [
                                openapi_client.models.status_value.StatusValue(
                                    name = '', 
                                    info = '', 
                                    value = '', )
                                ], )
                        ], ),
        )
        """

    def testReportStatusRequestContent(self):
        """Test ReportStatusRequestContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
