/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChannelState } from '../models/ChannelState';
import { Connection } from '../models/Connection';
import { IdAndValue } from '../models/IdAndValue';
import { SettingProfile } from '../models/SettingProfile';
import { HttpFile } from '../http/http';

export class ChannelConfiguration {
    'id': string;
    'state': ChannelState;
    'settings'?: Array<IdAndValue>;
    'settingProfile'?: SettingProfile;
    'connection'?: Connection;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "ChannelState",
            "format": ""
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "Array<IdAndValue>",
            "format": ""
        },
        {
            "name": "settingProfile",
            "baseName": "settingProfile",
            "type": "SettingProfile",
            "format": ""
        },
        {
            "name": "connection",
            "baseName": "connection",
            "type": "Connection",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChannelConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}


