/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChannelConfiguration } from '../models/ChannelConfiguration';
import { HttpFile } from '../http/http';

export class RouterDeviceConfiguration {
    'channels': Array<ChannelConfiguration>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channels",
            "baseName": "channels",
            "type": "Array<ChannelConfiguration>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RouterDeviceConfiguration.attributeTypeMap;
    }

    public constructor() {
    }
}
