/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RouterDeviceConfiguration } from '../models/RouterDeviceConfiguration';
import { HttpFile } from '../http/http';

export class SetConfigurationRequestContent {
    'configuration': RouterDeviceConfiguration;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "RouterDeviceConfiguration",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SetConfigurationRequestContent.attributeTypeMap;
    }

    public constructor() {
    }
}
