/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RistCaller } from '../models/RistCaller';
import { RistListener } from '../models/RistListener';
import { SrtCaller } from '../models/SrtCaller';
import { SrtListener } from '../models/SrtListener';
import { ZixiCaller } from '../models/ZixiCaller';
import { ZixiListener } from '../models/ZixiListener';
import { HttpFile } from '../http/http';

/**
 * @type TransportProtocol
 * Type
 * @export
 */
export type TransportProtocol = RistCaller | RistListener | SrtCaller | SrtListener | ZixiCaller | ZixiListener;

/**
* @type TransportProtocolClass
* @export
*/
export class TransportProtocolClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}





