/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ZixiListenerTransportProtocol } from '../models/ZixiListenerTransportProtocol';
import { HttpFile } from '../http/http';

export class ZixiListener {
    'zixiListener': ZixiListenerTransportProtocol;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "zixiListener",
            "baseName": "zixiListener",
            "type": "ZixiListenerTransportProtocol",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ZixiListener.attributeTypeMap;
    }

    public constructor() {
    }
}
