/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ChannelConfiguration.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ChannelConfiguration_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ChannelConfiguration_H_

#include <stdexcept>

#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/Connection.h"
#include "CppRestOpenAPIClient/model/ChannelState.h"
#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/IdAndValue.h"
#include <vector>
#include "CppRestOpenAPIClient/model/SettingProfile.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class IdAndValue;
class SettingProfile;
class Connection;


class  ChannelConfiguration
    : public ModelBase
{
public:
    ChannelConfiguration();
    virtual ~ChannelConfiguration();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ChannelConfiguration members


    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(const utility::string_t& value);

    std::shared_ptr<ChannelState> getState() const;
    bool stateIsSet() const;
    void unsetState();
    void setState(const std::shared_ptr<ChannelState>& value);

    std::vector<std::shared_ptr<IdAndValue>> getSettings() const;
    bool settingsIsSet() const;
    void unsetSettings();
    void setSettings(const std::vector<std::shared_ptr<IdAndValue>>& value);

    std::shared_ptr<SettingProfile> getSettingProfile() const;
    bool settingProfileIsSet() const;
    void unsetSettingProfile();
    void setSettingProfile(const std::shared_ptr<SettingProfile>& value);

    std::shared_ptr<Connection> getConnection() const;
    bool connectionIsSet() const;
    void unsetConnection();
    void setConnection(const std::shared_ptr<Connection>& value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;

    std::shared_ptr<ChannelState> m_State;
    bool m_StateIsSet;

    std::vector<std::shared_ptr<IdAndValue>> m_Settings;
    bool m_SettingsIsSet;

    std::shared_ptr<SettingProfile> m_SettingProfile;
    bool m_SettingProfileIsSet;

    std::shared_ptr<Connection> m_Connection;
    bool m_ConnectionIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ChannelConfiguration_H_ */
