/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ChannelState.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ChannelState_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ChannelState_H_


#include "CppRestOpenAPIClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  ChannelState
    : public ModelBase
{
public:
    ChannelState();
    ChannelState(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~ChannelState();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eChannelState
    {
        ACTIVE,
        IDLE,
    };

    eChannelState getValue() const;
    void setValue(eChannelState const value);

    protected:
        eChannelState m_value;
        std::map<eChannelState,utility::string_t> enumToStrMap = {
        { eChannelState::ACTIVE, _XPLATSTR("ACTIVE") },
        { eChannelState::IDLE, _XPLATSTR("IDLE") }
};
        std::map<utility::string_t,eChannelState> strToEnumMap = {
        { _XPLATSTR("ACTIVE"), eChannelState::ACTIVE },
        { _XPLATSTR("IDLE"), eChannelState::IDLE }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ChannelState_H_ */
