/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Connection.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Connection_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Connection_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/TransportProtocol.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class TransportProtocol;


class  Connection
    : public ModelBase
{
public:
    Connection();
    virtual ~Connection();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Connection members


    std::shared_ptr<TransportProtocol> getTransportProtocol() const;
    bool transportProtocolIsSet() const;
    void unsetTransportProtocol();
    void setTransportProtocol(const std::shared_ptr<TransportProtocol>& value);


protected:
    std::shared_ptr<TransportProtocol> m_TransportProtocol;
    bool m_TransportProtocolIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Connection_H_ */
