/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RistListener.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_RistListener_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_RistListener_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/RistListenerTransportProtocol.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class RistListenerTransportProtocol;


class  RistListener
    : public ModelBase
{
public:
    RistListener();
    virtual ~RistListener();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// RistListener members


    std::shared_ptr<RistListenerTransportProtocol> getRistListener() const;
    bool ristListenerIsSet() const;
    void unsetRistListener();
    void setRistListener(const std::shared_ptr<RistListenerTransportProtocol>& value);


protected:
    std::shared_ptr<RistListenerTransportProtocol> m_RistListener;
    bool m_RistListenerIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_RistListener_H_ */
