/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RistCallerTransportProtocol.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_RistCallerTransportProtocol_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_RistCallerTransportProtocol_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  RistCallerTransportProtocol
    : public ModelBase
{
public:
    RistCallerTransportProtocol();
    virtual ~RistCallerTransportProtocol();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// RistCallerTransportProtocol members


    utility::string_t getStreamId() const;
    bool streamIdIsSet() const;
    void unsetStreamId();
    void setStreamId(const utility::string_t& value);

    utility::string_t getMode() const;
    bool modeIsSet() const;
    void unsetMode();
    void setMode(const utility::string_t& value);

    utility::string_t getIp() const;
    bool ipIsSet() const;
    void unsetIp();
    void setIp(const utility::string_t& value);

    double getPort() const;
    bool portIsSet() const;
    void unsetPort();
    void setPort(double value);

    double getLatencyMs() const;
    bool latencyMsIsSet() const;
    void unsetLatencyMs();
    void setLatencyMs(double value);


protected:
    utility::string_t m_StreamId;
    bool m_StreamIdIsSet;

    utility::string_t m_Mode;
    bool m_ModeIsSet;

    utility::string_t m_Ip;
    bool m_IpIsSet;

    double m_Port;
    bool m_PortIsSet;

    double m_LatencyMs;
    bool m_LatencyMsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_RistCallerTransportProtocol_H_ */
