/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RistCaller.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_RistCaller_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_RistCaller_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/RistCallerTransportProtocol.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class RistCallerTransportProtocol;


class  RistCaller
    : public ModelBase
{
public:
    RistCaller();
    virtual ~RistCaller();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// RistCaller members


    std::shared_ptr<RistCallerTransportProtocol> getRistCaller() const;
    bool ristCallerIsSet() const;
    void unsetRistCaller();
    void setRistCaller(const std::shared_ptr<RistCallerTransportProtocol>& value);


protected:
    std::shared_ptr<RistCallerTransportProtocol> m_RistCaller;
    bool m_RistCallerIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_RistCaller_H_ */
