/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RouterDeviceConfiguration.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_RouterDeviceConfiguration_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_RouterDeviceConfiguration_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/ChannelConfiguration.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class ChannelConfiguration;


class  RouterDeviceConfiguration
    : public ModelBase
{
public:
    RouterDeviceConfiguration();
    virtual ~RouterDeviceConfiguration();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// RouterDeviceConfiguration members


    std::vector<std::shared_ptr<ChannelConfiguration>> getChannels() const;
    bool channelsIsSet() const;
    void unsetChannels();
    void setChannels(const std::vector<std::shared_ptr<ChannelConfiguration>>& value);


protected:
    std::vector<std::shared_ptr<ChannelConfiguration>> m_Channels;
    bool m_ChannelsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_RouterDeviceConfiguration_H_ */
