/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SetConfigurationRequestContent.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SetConfigurationRequestContent_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SetConfigurationRequestContent_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/RouterDeviceConfiguration.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class RouterDeviceConfiguration;


class  SetConfigurationRequestContent
    : public ModelBase
{
public:
    SetConfigurationRequestContent();
    virtual ~SetConfigurationRequestContent();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SetConfigurationRequestContent members


    std::shared_ptr<RouterDeviceConfiguration> getConfiguration() const;
    bool configurationIsSet() const;
    void unsetConfiguration();
    void setConfiguration(const std::shared_ptr<RouterDeviceConfiguration>& value);


protected:
    std::shared_ptr<RouterDeviceConfiguration> m_Configuration;
    bool m_ConfigurationIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SetConfigurationRequestContent_H_ */
