/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SrtCaller.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SrtCaller_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SrtCaller_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/SrtCallerTransportProtocol.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class SrtCallerTransportProtocol;


class  SrtCaller
    : public ModelBase
{
public:
    SrtCaller();
    virtual ~SrtCaller();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SrtCaller members


    std::shared_ptr<SrtCallerTransportProtocol> getSrtCaller() const;
    bool srtCallerIsSet() const;
    void unsetSrtCaller();
    void setSrtCaller(const std::shared_ptr<SrtCallerTransportProtocol>& value);


protected:
    std::shared_ptr<SrtCallerTransportProtocol> m_SrtCaller;
    bool m_SrtCallerIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SrtCaller_H_ */
