/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SrtListener.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SrtListener_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SrtListener_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/SrtListenerTransportProtocol.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class SrtListenerTransportProtocol;


class  SrtListener
    : public ModelBase
{
public:
    SrtListener();
    virtual ~SrtListener();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SrtListener members


    std::shared_ptr<SrtListenerTransportProtocol> getSrtListener() const;
    bool srtListenerIsSet() const;
    void unsetSrtListener();
    void setSrtListener(const std::shared_ptr<SrtListenerTransportProtocol>& value);


protected:
    std::shared_ptr<SrtListenerTransportProtocol> m_SrtListener;
    bool m_SrtListenerIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SrtListener_H_ */
