/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TransportProtocol.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_TransportProtocol_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_TransportProtocol_H_

#include <variant>

#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/ZixiCallerTransportProtocol.h"
#include "CppRestOpenAPIClient/model/RistListener.h"
#include "CppRestOpenAPIClient/model/ZixiListener.h"
#include "CppRestOpenAPIClient/model/RistListenerTransportProtocol.h"
#include "CppRestOpenAPIClient/model/RistCaller.h"
#include "CppRestOpenAPIClient/model/ZixiCaller.h"
#include "CppRestOpenAPIClient/model/SrtListener.h"
#include "CppRestOpenAPIClient/model/ZixiListenerTransportProtocol.h"
#include "CppRestOpenAPIClient/model/SrtCaller.h"
#include "CppRestOpenAPIClient/model/SrtCallerTransportProtocol.h"
#include "CppRestOpenAPIClient/model/RistCallerTransportProtocol.h"
#include "CppRestOpenAPIClient/model/SrtListenerTransportProtocol.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class SrtListenerTransportProtocol;
class SrtCallerTransportProtocol;
class RistListenerTransportProtocol;
class RistCallerTransportProtocol;
class ZixiListenerTransportProtocol;
class ZixiCallerTransportProtocol;


class  TransportProtocol
{
public:
    TransportProtocol() = default;
    ~TransportProtocol() = default;

    /////////////////////////////////////////////

    void validate();

    web::json::value toJson() const;

    template<typename Target>
    bool fromJson(const web::json::value& json) {
        // convert json to Target type
        Target target;
        if (!target.fromJson(json)) {
            return false;
        }

        m_variantValue = target;
        return true;
    }

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const;

    template<typename Target>
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) {
        // convert multipart to Target type
        Target target;
        if (!target.fromMultiPart(multipart, namePrefix)) {
            return false;
        }

        m_variantValue = target;
        return true;
    }

    /////////////////////////////////////////////
    /// TransportProtocol members

    using VariantType = std::variant<RistCaller, RistListener, SrtCaller, SrtListener, ZixiCaller, ZixiListener>;

    const VariantType& getVariant() const;
    void setVariant(VariantType value);

protected:
    VariantType m_variantValue;
};



}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_TransportProtocol_H_ */
