/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ZixiListener.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ZixiListener_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ZixiListener_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/ZixiListenerTransportProtocol.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class ZixiListenerTransportProtocol;


class  ZixiListener
    : public ModelBase
{
public:
    ZixiListener();
    virtual ~ZixiListener();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ZixiListener members


    std::shared_ptr<ZixiListenerTransportProtocol> getZixiListener() const;
    bool zixiListenerIsSet() const;
    void unsetZixiListener();
    void setZixiListener(const std::shared_ptr<ZixiListenerTransportProtocol>& value);


protected:
    std::shared_ptr<ZixiListenerTransportProtocol> m_ZixiListener;
    bool m_ZixiListenerIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ZixiListener_H_ */
