/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ZixiCaller.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ZixiCaller_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ZixiCaller_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/ZixiCallerTransportProtocol.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class ZixiCallerTransportProtocol;


class  ZixiCaller
    : public ModelBase
{
public:
    ZixiCaller();
    virtual ~ZixiCaller();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ZixiCaller members


    std::shared_ptr<ZixiCallerTransportProtocol> getZixiCaller() const;
    bool zixiCallerIsSet() const;
    void unsetZixiCaller();
    void setZixiCaller(const std::shared_ptr<ZixiCallerTransportProtocol>& value);


protected:
    std::shared_ptr<ZixiCallerTransportProtocol> m_ZixiCaller;
    bool m_ZixiCallerIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ZixiCaller_H_ */
