/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ChannelState.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

ChannelState::eChannelState toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(_XPLATSTR("ACTIVE")))
        return ChannelState::eChannelState::ACTIVE;
    if (val == utility::conversions::to_string_t(_XPLATSTR("IDLE")))
        return ChannelState::eChannelState::IDLE;
    return {};
}

EnumUnderlyingType fromEnum(ChannelState::eChannelState e)
{
    switch (e)
    {
    case ChannelState::eChannelState::ACTIVE:
        return _XPLATSTR("ACTIVE");
    case ChannelState::eChannelState::IDLE:
        return _XPLATSTR("IDLE");
    default:
        break;
    }
    return {};
}
}

ChannelState::ChannelState()
{
}

ChannelState::~ChannelState()
{
}

void ChannelState::validate()
{
    // TODO: implement validation
}

web::json::value ChannelState::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool ChannelState::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void ChannelState::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool ChannelState::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

ChannelState::eChannelState ChannelState::getValue() const
{
   return m_value;
}

void ChannelState::setValue(ChannelState::eChannelState const value)
{
   m_value = value;
}

ChannelState::ChannelState(utility::string_t str){
    setValue( strToEnumMap[str] );
}

}
}
}
}


