/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ChannelConfiguration.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ChannelConfiguration::ChannelConfiguration()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_StateIsSet = false;
    m_SettingsIsSet = false;
    m_SettingProfileIsSet = false;
    m_ConnectionIsSet = false;
}

ChannelConfiguration::~ChannelConfiguration()
{
}

void ChannelConfiguration::validate()
{
    // TODO: implement validation
}

web::json::value ChannelConfiguration::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_StateIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("state"))] = ModelBase::toJson(m_State);
    }
    if(m_SettingsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("settings"))] = ModelBase::toJson(m_Settings);
    }
    if(m_SettingProfileIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("settingProfile"))] = ModelBase::toJson(m_SettingProfile);
    }
    if(m_ConnectionIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("connection"))] = ModelBase::toJson(m_Connection);
    }

    return val;
}

bool ChannelConfiguration::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("state"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("state")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ChannelState> refVal_setState;
            ok &= ModelBase::fromJson(fieldValue, refVal_setState);
            setState(refVal_setState);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("settings"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("settings")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<IdAndValue>> refVal_setSettings;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSettings);
            setSettings(refVal_setSettings);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("settingProfile"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("settingProfile")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<SettingProfile> refVal_setSettingProfile;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSettingProfile);
            setSettingProfile(refVal_setSettingProfile);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("connection"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("connection")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Connection> refVal_setConnection;
            ok &= ModelBase::fromJson(fieldValue, refVal_setConnection);
            setConnection(refVal_setConnection);
            
        }
    }
    return ok;
}

void ChannelConfiguration::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_StateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("state")), m_State));
    }
    if(m_SettingsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("settings")), m_Settings));
    }
    if(m_SettingProfileIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("settingProfile")), m_SettingProfile));
    }
    if(m_ConnectionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("connection")), m_Connection));
    }
}

bool ChannelConfiguration::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("state"))))
    {
        std::shared_ptr<ChannelState> refVal_setState;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("state"))), refVal_setState );
        setState(refVal_setState);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("settings"))))
    {
        std::vector<std::shared_ptr<IdAndValue>> refVal_setSettings;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("settings"))), refVal_setSettings );
        setSettings(refVal_setSettings);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("settingProfile"))))
    {
        std::shared_ptr<SettingProfile> refVal_setSettingProfile;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("settingProfile"))), refVal_setSettingProfile );
        setSettingProfile(refVal_setSettingProfile);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("connection"))))
    {
        std::shared_ptr<Connection> refVal_setConnection;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("connection"))), refVal_setConnection );
        setConnection(refVal_setConnection);
    }
    return ok;
}


utility::string_t ChannelConfiguration::getId() const
{
    return m_Id;
}


void ChannelConfiguration::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool ChannelConfiguration::idIsSet() const
{
    return m_IdIsSet;
}

void ChannelConfiguration::unsetId()
{
    m_IdIsSet = false;
}
std::shared_ptr<ChannelState> ChannelConfiguration::getState() const
{
    return m_State;
}


void ChannelConfiguration::setState(const std::shared_ptr<ChannelState>& value)
{
    m_State = value;
    m_StateIsSet = true;
}

bool ChannelConfiguration::stateIsSet() const
{
    return m_StateIsSet;
}

void ChannelConfiguration::unsetState()
{
    m_StateIsSet = false;
}
std::vector<std::shared_ptr<IdAndValue>> ChannelConfiguration::getSettings() const
{
    return m_Settings;
}


void ChannelConfiguration::setSettings(const std::vector<std::shared_ptr<IdAndValue>>& value)
{
    m_Settings = value;
    m_SettingsIsSet = true;
}

bool ChannelConfiguration::settingsIsSet() const
{
    return m_SettingsIsSet;
}

void ChannelConfiguration::unsetSettings()
{
    m_SettingsIsSet = false;
}
std::shared_ptr<SettingProfile> ChannelConfiguration::getSettingProfile() const
{
    return m_SettingProfile;
}


void ChannelConfiguration::setSettingProfile(const std::shared_ptr<SettingProfile>& value)
{
    m_SettingProfile = value;
    m_SettingProfileIsSet = true;
}

bool ChannelConfiguration::settingProfileIsSet() const
{
    return m_SettingProfileIsSet;
}

void ChannelConfiguration::unsetSettingProfile()
{
    m_SettingProfileIsSet = false;
}
std::shared_ptr<Connection> ChannelConfiguration::getConnection() const
{
    return m_Connection;
}


void ChannelConfiguration::setConnection(const std::shared_ptr<Connection>& value)
{
    m_Connection = value;
    m_ConnectionIsSet = true;
}

bool ChannelConfiguration::connectionIsSet() const
{
    return m_ConnectionIsSet;
}

void ChannelConfiguration::unsetConnection()
{
    m_ConnectionIsSet = false;
}

}
}
}
}


