/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Connection.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Connection::Connection()
{
    m_TransportProtocolIsSet = false;
}

Connection::~Connection()
{
}

void Connection::validate()
{
    // TODO: implement validation
}

web::json::value Connection::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_TransportProtocolIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("transportProtocol"))] = ModelBase::toJson(m_TransportProtocol);
    }

    return val;
}

bool Connection::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("transportProtocol"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("transportProtocol")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<TransportProtocol> refVal_setTransportProtocol;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTransportProtocol);
            setTransportProtocol(refVal_setTransportProtocol);
            
        }
    }
    return ok;
}

void Connection::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_TransportProtocolIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("transportProtocol")), m_TransportProtocol));
    }
}

bool Connection::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("transportProtocol"))))
    {
        std::shared_ptr<TransportProtocol> refVal_setTransportProtocol;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("transportProtocol"))), refVal_setTransportProtocol );
        setTransportProtocol(refVal_setTransportProtocol);
    }
    return ok;
}


std::shared_ptr<TransportProtocol> Connection::getTransportProtocol() const
{
    return m_TransportProtocol;
}


void Connection::setTransportProtocol(const std::shared_ptr<TransportProtocol>& value)
{
    m_TransportProtocol = value;
    m_TransportProtocolIsSet = true;
}

bool Connection::transportProtocolIsSet() const
{
    return m_TransportProtocolIsSet;
}

void Connection::unsetTransportProtocol()
{
    m_TransportProtocolIsSet = false;
}

}
}
}
}


