/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/RistCaller.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RistCaller::RistCaller()
{
    m_RistCallerIsSet = false;
}

RistCaller::~RistCaller()
{
}

void RistCaller::validate()
{
    // TODO: implement validation
}

web::json::value RistCaller::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_RistCallerIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("ristCaller"))] = ModelBase::toJson(m_RistCaller);
    }

    return val;
}

bool RistCaller::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("ristCaller"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("ristCaller")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<RistCallerTransportProtocol> refVal_setRistCaller;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRistCaller);
            setRistCaller(refVal_setRistCaller);
            
        }
    }
    return ok;
}

void RistCaller::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_RistCallerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("ristCaller")), m_RistCaller));
    }
}

bool RistCaller::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("ristCaller"))))
    {
        std::shared_ptr<RistCallerTransportProtocol> refVal_setRistCaller;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("ristCaller"))), refVal_setRistCaller );
        setRistCaller(refVal_setRistCaller);
    }
    return ok;
}


std::shared_ptr<RistCallerTransportProtocol> RistCaller::getRistCaller() const
{
    return m_RistCaller;
}


void RistCaller::setRistCaller(const std::shared_ptr<RistCallerTransportProtocol>& value)
{
    m_RistCaller = value;
    m_RistCallerIsSet = true;
}

bool RistCaller::ristCallerIsSet() const
{
    return m_RistCallerIsSet;
}

void RistCaller::unsetRistCaller()
{
    m_RistCallerIsSet = false;
}

}
}
}
}


