/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/RistListener.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RistListener::RistListener()
{
    m_RistListenerIsSet = false;
}

RistListener::~RistListener()
{
}

void RistListener::validate()
{
    // TODO: implement validation
}

web::json::value RistListener::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_RistListenerIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("ristListener"))] = ModelBase::toJson(m_RistListener);
    }

    return val;
}

bool RistListener::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("ristListener"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("ristListener")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<RistListenerTransportProtocol> refVal_setRistListener;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRistListener);
            setRistListener(refVal_setRistListener);
            
        }
    }
    return ok;
}

void RistListener::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_RistListenerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("ristListener")), m_RistListener));
    }
}

bool RistListener::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("ristListener"))))
    {
        std::shared_ptr<RistListenerTransportProtocol> refVal_setRistListener;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("ristListener"))), refVal_setRistListener );
        setRistListener(refVal_setRistListener);
    }
    return ok;
}


std::shared_ptr<RistListenerTransportProtocol> RistListener::getRistListener() const
{
    return m_RistListener;
}


void RistListener::setRistListener(const std::shared_ptr<RistListenerTransportProtocol>& value)
{
    m_RistListener = value;
    m_RistListenerIsSet = true;
}

bool RistListener::ristListenerIsSet() const
{
    return m_RistListenerIsSet;
}

void RistListener::unsetRistListener()
{
    m_RistListenerIsSet = false;
}

}
}
}
}


