/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/RouterDeviceConfiguration.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RouterDeviceConfiguration::RouterDeviceConfiguration()
{
    m_ChannelsIsSet = false;
}

RouterDeviceConfiguration::~RouterDeviceConfiguration()
{
}

void RouterDeviceConfiguration::validate()
{
    // TODO: implement validation
}

web::json::value RouterDeviceConfiguration::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ChannelsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("channels"))] = ModelBase::toJson(m_Channels);
    }

    return val;
}

bool RouterDeviceConfiguration::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("channels"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("channels")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<ChannelConfiguration>> refVal_setChannels;
            ok &= ModelBase::fromJson(fieldValue, refVal_setChannels);
            setChannels(refVal_setChannels);
            
        }
    }
    return ok;
}

void RouterDeviceConfiguration::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ChannelsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("channels")), m_Channels));
    }
}

bool RouterDeviceConfiguration::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("channels"))))
    {
        std::vector<std::shared_ptr<ChannelConfiguration>> refVal_setChannels;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("channels"))), refVal_setChannels );
        setChannels(refVal_setChannels);
    }
    return ok;
}


std::vector<std::shared_ptr<ChannelConfiguration>> RouterDeviceConfiguration::getChannels() const
{
    return m_Channels;
}


void RouterDeviceConfiguration::setChannels(const std::vector<std::shared_ptr<ChannelConfiguration>>& value)
{
    m_Channels = value;
    m_ChannelsIsSet = true;
}

bool RouterDeviceConfiguration::channelsIsSet() const
{
    return m_ChannelsIsSet;
}

void RouterDeviceConfiguration::unsetChannels()
{
    m_ChannelsIsSet = false;
}

}
}
}
}


