/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/SetConfigurationRequestContent.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SetConfigurationRequestContent::SetConfigurationRequestContent()
{
    m_ConfigurationIsSet = false;
}

SetConfigurationRequestContent::~SetConfigurationRequestContent()
{
}

void SetConfigurationRequestContent::validate()
{
    // TODO: implement validation
}

web::json::value SetConfigurationRequestContent::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ConfigurationIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("configuration"))] = ModelBase::toJson(m_Configuration);
    }

    return val;
}

bool SetConfigurationRequestContent::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("configuration"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("configuration")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<RouterDeviceConfiguration> refVal_setConfiguration;
            ok &= ModelBase::fromJson(fieldValue, refVal_setConfiguration);
            setConfiguration(refVal_setConfiguration);
            
        }
    }
    return ok;
}

void SetConfigurationRequestContent::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ConfigurationIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("configuration")), m_Configuration));
    }
}

bool SetConfigurationRequestContent::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("configuration"))))
    {
        std::shared_ptr<RouterDeviceConfiguration> refVal_setConfiguration;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("configuration"))), refVal_setConfiguration );
        setConfiguration(refVal_setConfiguration);
    }
    return ok;
}


std::shared_ptr<RouterDeviceConfiguration> SetConfigurationRequestContent::getConfiguration() const
{
    return m_Configuration;
}


void SetConfigurationRequestContent::setConfiguration(const std::shared_ptr<RouterDeviceConfiguration>& value)
{
    m_Configuration = value;
    m_ConfigurationIsSet = true;
}

bool SetConfigurationRequestContent::configurationIsSet() const
{
    return m_ConfigurationIsSet;
}

void SetConfigurationRequestContent::unsetConfiguration()
{
    m_ConfigurationIsSet = false;
}

}
}
}
}


