/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/SrtCaller.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SrtCaller::SrtCaller()
{
    m_SrtCallerIsSet = false;
}

SrtCaller::~SrtCaller()
{
}

void SrtCaller::validate()
{
    // TODO: implement validation
}

web::json::value SrtCaller::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_SrtCallerIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("srtCaller"))] = ModelBase::toJson(m_SrtCaller);
    }

    return val;
}

bool SrtCaller::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("srtCaller"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("srtCaller")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<SrtCallerTransportProtocol> refVal_setSrtCaller;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSrtCaller);
            setSrtCaller(refVal_setSrtCaller);
            
        }
    }
    return ok;
}

void SrtCaller::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_SrtCallerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("srtCaller")), m_SrtCaller));
    }
}

bool SrtCaller::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("srtCaller"))))
    {
        std::shared_ptr<SrtCallerTransportProtocol> refVal_setSrtCaller;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("srtCaller"))), refVal_setSrtCaller );
        setSrtCaller(refVal_setSrtCaller);
    }
    return ok;
}


std::shared_ptr<SrtCallerTransportProtocol> SrtCaller::getSrtCaller() const
{
    return m_SrtCaller;
}


void SrtCaller::setSrtCaller(const std::shared_ptr<SrtCallerTransportProtocol>& value)
{
    m_SrtCaller = value;
    m_SrtCallerIsSet = true;
}

bool SrtCaller::srtCallerIsSet() const
{
    return m_SrtCallerIsSet;
}

void SrtCaller::unsetSrtCaller()
{
    m_SrtCallerIsSet = false;
}

}
}
}
}


