/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/SrtListener.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SrtListener::SrtListener()
{
    m_SrtListenerIsSet = false;
}

SrtListener::~SrtListener()
{
}

void SrtListener::validate()
{
    // TODO: implement validation
}

web::json::value SrtListener::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_SrtListenerIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("srtListener"))] = ModelBase::toJson(m_SrtListener);
    }

    return val;
}

bool SrtListener::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("srtListener"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("srtListener")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<SrtListenerTransportProtocol> refVal_setSrtListener;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSrtListener);
            setSrtListener(refVal_setSrtListener);
            
        }
    }
    return ok;
}

void SrtListener::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_SrtListenerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("srtListener")), m_SrtListener));
    }
}

bool SrtListener::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("srtListener"))))
    {
        std::shared_ptr<SrtListenerTransportProtocol> refVal_setSrtListener;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("srtListener"))), refVal_setSrtListener );
        setSrtListener(refVal_setSrtListener);
    }
    return ok;
}


std::shared_ptr<SrtListenerTransportProtocol> SrtListener::getSrtListener() const
{
    return m_SrtListener;
}


void SrtListener::setSrtListener(const std::shared_ptr<SrtListenerTransportProtocol>& value)
{
    m_SrtListener = value;
    m_SrtListenerIsSet = true;
}

bool SrtListener::srtListenerIsSet() const
{
    return m_SrtListenerIsSet;
}

void SrtListener::unsetSrtListener()
{
    m_SrtListenerIsSet = false;
}

}
}
}
}


