/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/TransportProtocol.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

void TransportProtocol::validate()
{
    // TODO: implement validation
}

const TransportProtocol::VariantType& TransportProtocol::getVariant() const
{
    return m_variantValue;
}

void TransportProtocol::setVariant(TransportProtocol::VariantType value)
{
    m_variantValue = value;
}

web::json::value TransportProtocol::toJson() const
{
    web::json::value val = web::json::value::object();

    std::visit([&](auto&& arg) {
        using T = std::decay_t<decltype(arg)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
            val = web::json::value::null();
        } else {
            val = arg.toJson();
        }
    }, m_variantValue);

    return val;
}

void TransportProtocol::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    std::visit([&](auto&& arg) {
        using T = std::decay_t<decltype(arg)>;
        if constexpr (!std::is_same_v<T, std::monostate>) {
          arg.toMultipart(multipart, prefix);
        }
    }, m_variantValue);
}

template bool TransportProtocol::fromJson<RistCaller>(const web::json::value& json);
template bool TransportProtocol::fromMultiPart<RistCaller>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);
template bool TransportProtocol::fromJson<RistListener>(const web::json::value& json);
template bool TransportProtocol::fromMultiPart<RistListener>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);
template bool TransportProtocol::fromJson<SrtCaller>(const web::json::value& json);
template bool TransportProtocol::fromMultiPart<SrtCaller>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);
template bool TransportProtocol::fromJson<SrtListener>(const web::json::value& json);
template bool TransportProtocol::fromMultiPart<SrtListener>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);
template bool TransportProtocol::fromJson<ZixiCaller>(const web::json::value& json);
template bool TransportProtocol::fromMultiPart<ZixiCaller>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);
template bool TransportProtocol::fromJson<ZixiListener>(const web::json::value& json);
template bool TransportProtocol::fromMultiPart<ZixiListener>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);

}
}
}
}


