/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ZixiCaller.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ZixiCaller::ZixiCaller()
{
    m_ZixiCallerIsSet = false;
}

ZixiCaller::~ZixiCaller()
{
}

void ZixiCaller::validate()
{
    // TODO: implement validation
}

web::json::value ZixiCaller::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ZixiCallerIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("zixiCaller"))] = ModelBase::toJson(m_ZixiCaller);
    }

    return val;
}

bool ZixiCaller::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("zixiCaller"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("zixiCaller")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ZixiCallerTransportProtocol> refVal_setZixiCaller;
            ok &= ModelBase::fromJson(fieldValue, refVal_setZixiCaller);
            setZixiCaller(refVal_setZixiCaller);
            
        }
    }
    return ok;
}

void ZixiCaller::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ZixiCallerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("zixiCaller")), m_ZixiCaller));
    }
}

bool ZixiCaller::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("zixiCaller"))))
    {
        std::shared_ptr<ZixiCallerTransportProtocol> refVal_setZixiCaller;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("zixiCaller"))), refVal_setZixiCaller );
        setZixiCaller(refVal_setZixiCaller);
    }
    return ok;
}


std::shared_ptr<ZixiCallerTransportProtocol> ZixiCaller::getZixiCaller() const
{
    return m_ZixiCaller;
}


void ZixiCaller::setZixiCaller(const std::shared_ptr<ZixiCallerTransportProtocol>& value)
{
    m_ZixiCaller = value;
    m_ZixiCallerIsSet = true;
}

bool ZixiCaller::zixiCallerIsSet() const
{
    return m_ZixiCallerIsSet;
}

void ZixiCaller::unsetZixiCaller()
{
    m_ZixiCallerIsSet = false;
}

}
}
}
}


