/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ZixiListener.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ZixiListener::ZixiListener()
{
    m_ZixiListenerIsSet = false;
}

ZixiListener::~ZixiListener()
{
}

void ZixiListener::validate()
{
    // TODO: implement validation
}

web::json::value ZixiListener::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ZixiListenerIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("zixiListener"))] = ModelBase::toJson(m_ZixiListener);
    }

    return val;
}

bool ZixiListener::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("zixiListener"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("zixiListener")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ZixiListenerTransportProtocol> refVal_setZixiListener;
            ok &= ModelBase::fromJson(fieldValue, refVal_setZixiListener);
            setZixiListener(refVal_setZixiListener);
            
        }
    }
    return ok;
}

void ZixiListener::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ZixiListenerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("zixiListener")), m_ZixiListener));
    }
}

bool ZixiListener::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("zixiListener"))))
    {
        std::shared_ptr<ZixiListenerTransportProtocol> refVal_setZixiListener;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("zixiListener"))), refVal_setZixiListener );
        setZixiListener(refVal_setZixiListener);
    }
    return ok;
}


std::shared_ptr<ZixiListenerTransportProtocol> ZixiListener::getZixiListener() const
{
    return m_ZixiListener;
}


void ZixiListener::setZixiListener(const std::shared_ptr<ZixiListenerTransportProtocol>& value)
{
    m_ZixiListener = value;
    m_ZixiListenerIsSet = true;
}

bool ZixiListener::zixiListenerIsSet() const
{
    return m_ZixiListenerIsSet;
}

void ZixiListener::unsetZixiListener()
{
    m_ZixiListenerIsSet = false;
}

}
}
}
}


