/**
 * ConfigurationService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ZixiCallerTransportProtocol.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ZixiCallerTransportProtocol::ZixiCallerTransportProtocol()
{
    m_StreamId = utility::conversions::to_string_t("");
    m_StreamIdIsSet = false;
    m_Ip = utility::conversions::to_string_t("");
    m_IpIsSet = false;
    m_Port = 0.0;
    m_PortIsSet = false;
    m_LatencyMs = 0.0;
    m_LatencyMsIsSet = false;
}

ZixiCallerTransportProtocol::~ZixiCallerTransportProtocol()
{
}

void ZixiCallerTransportProtocol::validate()
{
    // TODO: implement validation
}

web::json::value ZixiCallerTransportProtocol::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StreamIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("streamId"))] = ModelBase::toJson(m_StreamId);
    }
    if(m_IpIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("ip"))] = ModelBase::toJson(m_Ip);
    }
    if(m_PortIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("port"))] = ModelBase::toJson(m_Port);
    }
    if(m_LatencyMsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("latencyMs"))] = ModelBase::toJson(m_LatencyMs);
    }

    return val;
}

bool ZixiCallerTransportProtocol::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("streamId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("streamId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStreamId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStreamId);
            setStreamId(refVal_setStreamId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("ip"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("ip")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIp;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIp);
            setIp(refVal_setIp);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("port"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("port")));
        if(!fieldValue.is_null())
        {
            double refVal_setPort;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPort);
            setPort(refVal_setPort);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("latencyMs"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("latencyMs")));
        if(!fieldValue.is_null())
        {
            double refVal_setLatencyMs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLatencyMs);
            setLatencyMs(refVal_setLatencyMs);
            
        }
    }
    return ok;
}

void ZixiCallerTransportProtocol::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_StreamIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("streamId")), m_StreamId));
    }
    if(m_IpIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("ip")), m_Ip));
    }
    if(m_PortIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("port")), m_Port));
    }
    if(m_LatencyMsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("latencyMs")), m_LatencyMs));
    }
}

bool ZixiCallerTransportProtocol::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("streamId"))))
    {
        utility::string_t refVal_setStreamId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("streamId"))), refVal_setStreamId );
        setStreamId(refVal_setStreamId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("ip"))))
    {
        utility::string_t refVal_setIp;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("ip"))), refVal_setIp );
        setIp(refVal_setIp);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("port"))))
    {
        double refVal_setPort;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("port"))), refVal_setPort );
        setPort(refVal_setPort);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("latencyMs"))))
    {
        double refVal_setLatencyMs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("latencyMs"))), refVal_setLatencyMs );
        setLatencyMs(refVal_setLatencyMs);
    }
    return ok;
}


utility::string_t ZixiCallerTransportProtocol::getStreamId() const
{
    return m_StreamId;
}


void ZixiCallerTransportProtocol::setStreamId(const utility::string_t& value)
{
    m_StreamId = value;
    m_StreamIdIsSet = true;
}

bool ZixiCallerTransportProtocol::streamIdIsSet() const
{
    return m_StreamIdIsSet;
}

void ZixiCallerTransportProtocol::unsetStreamId()
{
    m_StreamIdIsSet = false;
}
utility::string_t ZixiCallerTransportProtocol::getIp() const
{
    return m_Ip;
}


void ZixiCallerTransportProtocol::setIp(const utility::string_t& value)
{
    m_Ip = value;
    m_IpIsSet = true;
}

bool ZixiCallerTransportProtocol::ipIsSet() const
{
    return m_IpIsSet;
}

void ZixiCallerTransportProtocol::unsetIp()
{
    m_IpIsSet = false;
}
double ZixiCallerTransportProtocol::getPort() const
{
    return m_Port;
}

void ZixiCallerTransportProtocol::setPort(double value)
{
    m_Port = value;
    m_PortIsSet = true;
}

bool ZixiCallerTransportProtocol::portIsSet() const
{
    return m_PortIsSet;
}

void ZixiCallerTransportProtocol::unsetPort()
{
    m_PortIsSet = false;
}
double ZixiCallerTransportProtocol::getLatencyMs() const
{
    return m_LatencyMs;
}

void ZixiCallerTransportProtocol::setLatencyMs(double value)
{
    m_LatencyMs = value;
    m_LatencyMsIsSet = true;
}

bool ZixiCallerTransportProtocol::latencyMsIsSet() const
{
    return m_LatencyMsIsSet;
}

void ZixiCallerTransportProtocol::unsetLatencyMs()
{
    m_LatencyMsIsSet = false;
}

}
}
}
}


