# coding: utf-8

"""
    HostServiceApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from internal_api_client.models.protocol_version import ProtocolVersion

class TestProtocolVersion(unittest.TestCase):
    """ProtocolVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProtocolVersion(self):
        """Test ProtocolVersion"""
        # inst = ProtocolVersion()

if __name__ == '__main__':
    unittest.main()
