# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.channel_type import ChannelType
from openapi_client.models.profile import Profile
from openapi_client.models.setting import Setting
from openapi_client.models.supported_protocol import SupportedProtocol
from typing import Optional, Set
from typing_extensions import Self

class Channel(BaseModel):
    """
    Channel
    """ # noqa: E501
    name: StrictStr
    id: StrictStr
    channel_type: Optional[ChannelType] = Field(default=None, alias="channelType")
    settings: Optional[List[Setting]] = None
    setting_profiles: Optional[List[Profile]] = Field(default=None, alias="settingProfiles")
    connection_protocols: Optional[List[SupportedProtocol]] = Field(default=None, alias="connectionProtocols")
    __properties: ClassVar[List[str]] = ["name", "id", "channelType", "settings", "settingProfiles", "connectionProtocols"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Channel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in settings (list)
        _items = []
        if self.settings:
            for _item_settings in self.settings:
                if _item_settings:
                    _items.append(_item_settings.to_dict())
            _dict['settings'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in setting_profiles (list)
        _items = []
        if self.setting_profiles:
            for _item_setting_profiles in self.setting_profiles:
                if _item_setting_profiles:
                    _items.append(_item_setting_profiles.to_dict())
            _dict['settingProfiles'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Channel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "id": obj.get("id"),
            "channelType": obj.get("channelType"),
            "settings": [Setting.from_dict(_item) for _item in obj["settings"]] if obj.get("settings") is not None else None,
            "settingProfiles": [Profile.from_dict(_item) for _item in obj["settingProfiles"]] if obj.get("settingProfiles") is not None else None,
            "connectionProtocols": obj.get("connectionProtocols")
        })
        return _obj


