# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SupportedProtocol(str, Enum):
    """
    SupportedProtocol
    """

    """
    allowed enum values
    """
    SRT_LISTENER = 'srt_listener'
    SRT_CALLER = 'srt_caller'
    ZIXI_LISTENER = 'zixi_listener'
    ZIXI_CALLER = 'zixi_caller'
    RIST_CALLER = 'rist_caller'
    RIST_LISTENER = 'rist_listener'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SupportedProtocol from a JSON string"""
        return cls(json.loads(json_str))


