# coding: utf-8

"""
    ConfigurationService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.channel_configuration import ChannelConfiguration

class TestChannelConfiguration(unittest.TestCase):
    """ChannelConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChannelConfiguration:
        """Test ChannelConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChannelConfiguration`
        """
        model = ChannelConfiguration()
        if include_optional:
            return ChannelConfiguration(
                id = '',
                state = 'ACTIVE',
                settings = [
                    openapi_client.models.id_and_value.IdAndValue(
                        id = '', 
                        value = '', )
                    ],
                setting_profile = openapi_client.models.setting_profile.SettingProfile(
                    id = '', ),
                connection = openapi_client.models.connection.Connection(
                    transport_protocol = null, )
            )
        else:
            return ChannelConfiguration(
                id = '',
                state = 'ACTIVE',
        )
        """

    def testChannelConfiguration(self):
        """Test ChannelConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
