# coding: utf-8

"""
    ConfigurationService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.rist_listener_transport_protocol import RistListenerTransportProtocol

class TestRistListenerTransportProtocol(unittest.TestCase):
    """RistListenerTransportProtocol unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RistListenerTransportProtocol:
        """Test RistListenerTransportProtocol
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RistListenerTransportProtocol`
        """
        model = RistListenerTransportProtocol()
        if include_optional:
            return RistListenerTransportProtocol(
                stream_id = '',
                mode = '',
                ip = '',
                port = 1.337,
                latency_ms = 1.337
            )
        else:
            return RistListenerTransportProtocol(
                mode = '',
                ip = '',
                port = 1.337,
                latency_ms = 1.337,
        )
        """

    def testRistListenerTransportProtocol(self):
        """Test RistListenerTransportProtocol"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
