# coding: utf-8

"""
    ConfigurationService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.srt_listener_transport_protocol import SrtListenerTransportProtocol

class TestSrtListenerTransportProtocol(unittest.TestCase):
    """SrtListenerTransportProtocol unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SrtListenerTransportProtocol:
        """Test SrtListenerTransportProtocol
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SrtListenerTransportProtocol`
        """
        model = SrtListenerTransportProtocol()
        if include_optional:
            return SrtListenerTransportProtocol(
                stream_id = '',
                ip = '',
                port = 1.337,
                latency_ms = 1.337
            )
        else:
            return SrtListenerTransportProtocol(
                ip = '',
                port = 1.337,
                latency_ms = 1.337,
        )
        """

    def testSrtListenerTransportProtocol(self):
        """Test SrtListenerTransportProtocol"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
