# coding: utf-8

"""
    ConfigurationService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.router_device_configuration import RouterDeviceConfiguration

class TestRouterDeviceConfiguration(unittest.TestCase):
    """RouterDeviceConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RouterDeviceConfiguration:
        """Test RouterDeviceConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RouterDeviceConfiguration`
        """
        model = RouterDeviceConfiguration()
        if include_optional:
            return RouterDeviceConfiguration(
                channels = [
                    openapi_client.models.channel_configuration.ChannelConfiguration(
                        id = '', 
                        state = 'ACTIVE', 
                        settings = [
                            openapi_client.models.id_and_value.IdAndValue(
                                id = '', 
                                value = '', )
                            ], 
                        setting_profile = openapi_client.models.setting_profile.SettingProfile(
                            id = '', ), 
                        connection = openapi_client.models.connection.Connection(
                            transport_protocol = null, ), )
                    ]
            )
        else:
            return RouterDeviceConfiguration(
                channels = [
                    openapi_client.models.channel_configuration.ChannelConfiguration(
                        id = '', 
                        state = 'ACTIVE', 
                        settings = [
                            openapi_client.models.id_and_value.IdAndValue(
                                id = '', 
                                value = '', )
                            ], 
                        setting_profile = openapi_client.models.setting_profile.SettingProfile(
                            id = '', ), 
                        connection = openapi_client.models.connection.Connection(
                            transport_protocol = null, ), )
                    ],
        )
        """

    def testRouterDeviceConfiguration(self):
        """Test RouterDeviceConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
