# coding: utf-8

"""
    ConfigurationService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_configuration(self) -> None:
        """Test case for get_configuration

        """
        pass

    def test_set_configuration(self) -> None:
        """Test case for set_configuration

        """
        pass


if __name__ == '__main__':
    unittest.main()
