# coding: utf-8

# flake8: noqa
"""
    HostServiceApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from internal_api_client.models.auth_status import AuthStatus
from internal_api_client.models.authenticate_request_content import AuthenticateRequestContent
from internal_api_client.models.authenticate_response_content import AuthenticateResponseContent
from internal_api_client.models.deprovision_device_request_content import DeprovisionDeviceRequestContent
from internal_api_client.models.deprovision_reason import DeprovisionReason
from internal_api_client.models.failure import Failure
from internal_api_client.models.get_host_config_response_content import GetHostConfigResponseContent
from internal_api_client.models.get_version_response_content import GetVersionResponseContent
from internal_api_client.models.host_settings import HostSettings
from internal_api_client.models.pair_failure_data import PairFailureData
from internal_api_client.models.pair_failure_reason import PairFailureReason
from internal_api_client.models.pair_request_content import PairRequestContent
from internal_api_client.models.pair_response_content import PairResponseContent
from internal_api_client.models.pair_result import PairResult
from internal_api_client.models.pair_success_data import PairSuccessData
from internal_api_client.models.protocol_version import ProtocolVersion
from internal_api_client.models.request_log_request_content import RequestLogRequestContent
from internal_api_client.models.request_thumbnail_request_content import RequestThumbnailRequestContent
from internal_api_client.models.rotate_certificates_request_content import RotateCertificatesRequestContent
from internal_api_client.models.success import Success
from internal_api_client.models.thumbnail_request import ThumbnailRequest

