# coding: utf-8

"""
    HostServiceApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PairFailureReason(str, Enum):
    """
    PairFailureReason
    """

    """
    allowed enum values
    """
    HOST_ID_MISMATCH = 'HOST_ID_MISMATCH'
    VERSION_NOT_SUPPORTED = 'VERSION_NOT_SUPPORTED'
    DEVICE_TYPE_NOT_SUPPORTED = 'DEVICE_TYPE_NOT_SUPPORTED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PairFailureReason from a JSON string"""
        return cls(json.loads(json_str))


