# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.device_status import DeviceStatus

class TestDeviceStatus(unittest.TestCase):
    """DeviceStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceStatus:
        """Test DeviceStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceStatus`
        """
        model = DeviceStatus()
        if include_optional:
            return DeviceStatus(
                status = [
                    openapi_client.models.status_value.StatusValue(
                        name = '', 
                        info = '', 
                        value = '', )
                    ],
                channels = [
                    openapi_client.models.channel_status.ChannelStatus(
                        id = '', 
                        state = 'ACTIVE', 
                        status = [
                            openapi_client.models.status_value.StatusValue(
                                name = '', 
                                info = '', 
                                value = '', )
                            ], )
                    ]
            )
        else:
            return DeviceStatus(
                status = [
                    openapi_client.models.status_value.StatusValue(
                        name = '', 
                        info = '', 
                        value = '', )
                    ],
        )
        """

    def testDeviceStatus(self):
        """Test DeviceStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
