# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.model_none import ModelNone

class TestModelNone(unittest.TestCase):
    """ModelNone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelNone:
        """Test ModelNone
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelNone`
        """
        model = ModelNone()
        if include_optional:
            return ModelNone(
                var_none = openapi_client.models.unit.Unit()
            )
        else:
            return ModelNone(
                var_none = openapi_client.models.unit.Unit(),
        )
        """

    def testModelNone(self):
        """Test ModelNone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
