# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.zixi_listener import ZixiListener

class TestZixiListener(unittest.TestCase):
    """ZixiListener unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ZixiListener:
        """Test ZixiListener
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ZixiListener`
        """
        model = ZixiListener()
        if include_optional:
            return ZixiListener(
                zixi_listener = openapi_client.models.zixi_listener_transport_protocol.ZixiListenerTransportProtocol(
                    stream_id = '', 
                    port = 1.337, 
                    minimum_latency_milliseconds = 1.337, 
                    encryption = null, 
                    interface = '', )
            )
        else:
            return ZixiListener(
                zixi_listener = openapi_client.models.zixi_listener_transport_protocol.ZixiListenerTransportProtocol(
                    stream_id = '', 
                    port = 1.337, 
                    minimum_latency_milliseconds = 1.337, 
                    encryption = null, 
                    interface = '', ),
        )
        """

    def testZixiListener(self):
        """Test ZixiListener"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
