# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_configuration_response_content import GetConfigurationResponseContent

class TestGetConfigurationResponseContent(unittest.TestCase):
    """GetConfigurationResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetConfigurationResponseContent:
        """Test GetConfigurationResponseContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetConfigurationResponseContent`
        """
        model = GetConfigurationResponseContent()
        if include_optional:
            return GetConfigurationResponseContent(
                success = True,
                state = '',
                message = '',
                error = openapi_client.models.error_details.ErrorDetails(
                    type = '', 
                    message = '', 
                    details = '', ),
                configuration = openapi_client.models.configuration_data.ConfigurationData(
                    update_id = '', 
                    payload = null, )
            )
        else:
            return GetConfigurationResponseContent(
                success = True,
                state = '',
                message = '',
        )
        """

    def testGetConfigurationResponseContent(self):
        """Test GetConfigurationResponseContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
