# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.encryption_aes128 import EncryptionAes128

class TestEncryptionAes128(unittest.TestCase):
    """EncryptionAes128 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EncryptionAes128:
        """Test EncryptionAes128
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EncryptionAes128`
        """
        model = EncryptionAes128()
        if include_optional:
            return EncryptionAes128(
                passcode = '2012345678910111213141516171819202122232425262728293031'
            )
        else:
            return EncryptionAes128(
                passcode = '2012345678910111213141516171819202122232425262728293031',
        )
        """

    def testEncryptionAes128(self):
        """Test EncryptionAes128"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
