# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.aes128 import Aes128

class TestAes128(unittest.TestCase):
    """Aes128 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Aes128:
        """Test Aes128
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Aes128`
        """
        model = Aes128()
        if include_optional:
            return Aes128(
                aes128 = openapi_client.models.encryption_aes128.EncryptionAes128(
                    passcode = '2012345678910111213141516171819202122232425262728293031', )
            )
        else:
            return Aes128(
                aes128 = openapi_client.models.encryption_aes128.EncryptionAes128(
                    passcode = '2012345678910111213141516171819202122232425262728293031', ),
        )
        """

    def testAes128(self):
        """Test Aes128"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
