# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.encryption_aes256 import EncryptionAes256

class TestEncryptionAes256(unittest.TestCase):
    """EncryptionAes256 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EncryptionAes256:
        """Test EncryptionAes256
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EncryptionAes256`
        """
        model = EncryptionAes256()
        if include_optional:
            return EncryptionAes256(
                passcode = '20123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263'
            )
        else:
            return EncryptionAes256(
                passcode = '20123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263',
        )
        """

    def testEncryptionAes256(self):
        """Test EncryptionAes256"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
