# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.rist_stream_identifier import RistStreamIdentifier

class TestRistStreamIdentifier(unittest.TestCase):
    """RistStreamIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RistStreamIdentifier:
        """Test RistStreamIdentifier
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RistStreamIdentifier`
        """
        model = RistStreamIdentifier()
        if include_optional:
            return RistStreamIdentifier(
                synchronization_source = 1.337,
                stream_id = ''
            )
        else:
            return RistStreamIdentifier(
                synchronization_source = 1.337,
                stream_id = '',
        )
        """

    def testRistStreamIdentifier(self):
        """Test RistStreamIdentifier"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
