# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.encryption import Encryption

class TestEncryption(unittest.TestCase):
    """Encryption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Encryption:
        """Test Encryption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Encryption`
        """
        model = Encryption()
        if include_optional:
            return Encryption(
                aes128 = openapi_client.models.encryption_aes128.EncryptionAes128(
                    passcode = '2012345678910111213141516171819202122232425262728293031', ),
                aes256 = openapi_client.models.encryption_aes256.EncryptionAes256(
                    passcode = '20123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263', )
            )
        else:
            return Encryption(
                aes128 = openapi_client.models.encryption_aes128.EncryptionAes128(
                    passcode = '2012345678910111213141516171819202122232425262728293031', ),
                aes256 = openapi_client.models.encryption_aes256.EncryptionAes256(
                    passcode = '20123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263', ),
        )
        """

    def testEncryption(self):
        """Test Encryption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
