# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.settings_choice import SettingsChoice

class TestSettingsChoice(unittest.TestCase):
    """SettingsChoice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingsChoice:
        """Test SettingsChoice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingsChoice`
        """
        model = SettingsChoice()
        if include_optional:
            return SettingsChoice(
                simple_settings = [
                    openapi_client.models.id_and_value.IdAndValue(
                        key = '', 
                        value = '', )
                    ],
                profile = openapi_client.models.setting_profile.SettingProfile(
                    id = '', )
            )
        else:
            return SettingsChoice(
                simple_settings = [
                    openapi_client.models.id_and_value.IdAndValue(
                        key = '', 
                        value = '', )
                    ],
                profile = openapi_client.models.setting_profile.SettingProfile(
                    id = '', ),
        )
        """

    def testSettingsChoice(self):
        """Test SettingsChoice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
