# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.rist_caller import RistCaller

class TestRistCaller(unittest.TestCase):
    """RistCaller unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RistCaller:
        """Test RistCaller
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RistCaller`
        """
        model = RistCaller()
        if include_optional:
            return RistCaller(
                rist_caller = openapi_client.models.rist_caller_transport_protocol.RistCallerTransportProtocol(
                    stream_id = '', 
                    mode = '', 
                    ip = '', 
                    port = 1.337, 
                    latency_ms = 1.337, )
            )
        else:
            return RistCaller(
                rist_caller = openapi_client.models.rist_caller_transport_protocol.RistCallerTransportProtocol(
                    stream_id = '', 
                    mode = '', 
                    ip = '', 
                    port = 1.337, 
                    latency_ms = 1.337, ),
        )
        """

    def testRistCaller(self):
        """Test RistCaller"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
