# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.connect_request_content import ConnectRequestContent

class TestConnectRequestContent(unittest.TestCase):
    """ConnectRequestContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectRequestContent:
        """Test ConnectRequestContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectRequestContent`
        """
        model = ConnectRequestContent()
        if include_optional:
            return ConnectRequestContent(
                registration = openapi_client.models.device_registration.DeviceRegistration(
                    channels = [
                        openapi_client.models.channel.Channel(
                            name = '', 
                            id = '', 
                            channel_type = 'SOURCE', 
                            simple_settings = [
                                openapi_client.models.setting.Setting(
                                    id = '', 
                                    name = '', 
                                    info = '', 
                                    enums = openapi_client.models.enum_values.EnumValues(
                                        values = [
                                            ''
                                            ], 
                                        default_value = '', ), 
                                    ranges = openapi_client.models.range_values.RangeValues(
                                        min = 1.337, 
                                        max = 1.337, 
                                        default_value = 1.337, ), )
                                ], 
                            profile_setting = [
                                openapi_client.models.profile.Profile(
                                    name = '', 
                                    id = '', 
                                    info = '', )
                                ], 
                            connection_protocols = [
                                'srt_listener'
                                ], )
                        ], 
                    simple_settings = [
                        openapi_client.models.setting.Setting(
                            id = '', 
                            name = '', 
                            info = '', )
                        ], 
                    thumbnails = [
                        openapi_client.models.thumbnail.Thumbnail(
                            name = '', 
                            id = '', 
                            local_path = '', )
                        ], ),
                host_id = ''
            )
        else:
            return ConnectRequestContent(
                registration = openapi_client.models.device_registration.DeviceRegistration(
                    channels = [
                        openapi_client.models.channel.Channel(
                            name = '', 
                            id = '', 
                            channel_type = 'SOURCE', 
                            simple_settings = [
                                openapi_client.models.setting.Setting(
                                    id = '', 
                                    name = '', 
                                    info = '', 
                                    enums = openapi_client.models.enum_values.EnumValues(
                                        values = [
                                            ''
                                            ], 
                                        default_value = '', ), 
                                    ranges = openapi_client.models.range_values.RangeValues(
                                        min = 1.337, 
                                        max = 1.337, 
                                        default_value = 1.337, ), )
                                ], 
                            profile_setting = [
                                openapi_client.models.profile.Profile(
                                    name = '', 
                                    id = '', 
                                    info = '', )
                                ], 
                            connection_protocols = [
                                'srt_listener'
                                ], )
                        ], 
                    simple_settings = [
                        openapi_client.models.setting.Setting(
                            id = '', 
                            name = '', 
                            info = '', )
                        ], 
                    thumbnails = [
                        openapi_client.models.thumbnail.Thumbnail(
                            name = '', 
                            id = '', 
                            local_path = '', )
                        ], ),
                host_id = '',
        )
        """

    def testConnectRequestContent(self):
        """Test ConnectRequestContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
