# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.channel_state import ChannelState

class TestChannelState(unittest.TestCase):
    """ChannelState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelState(self):
        """Test ChannelState"""
        # inst = ChannelState()

if __name__ == '__main__':
    unittest.main()
