# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.zixi_listener_transport_protocol import ZixiListenerTransportProtocol

class TestZixiListenerTransportProtocol(unittest.TestCase):
    """ZixiListenerTransportProtocol unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ZixiListenerTransportProtocol:
        """Test ZixiListenerTransportProtocol
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ZixiListenerTransportProtocol`
        """
        model = ZixiListenerTransportProtocol()
        if include_optional:
            return ZixiListenerTransportProtocol(
                stream_id = '',
                ip = '',
                port = 1.337,
                latency_ms = 1.337
            )
        else:
            return ZixiListenerTransportProtocol(
                stream_id = '',
                ip = '',
                port = 1.337,
                latency_ms = 1.337,
        )
        """

    def testZixiListenerTransportProtocol(self):
        """Test ZixiListenerTransportProtocol"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
