# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.encryption import Encryption
from openapi_client.models.rist_stream_identifier import RistStreamIdentifier
from typing import Optional, Set
from typing_extensions import Self

class RistListenerTransportProtocol(BaseModel):
    """
    RistListenerTransportProtocol
    """ # noqa: E501
    stream_id: Optional[RistStreamIdentifier] = Field(default=None, alias="streamId")
    port: Union[StrictFloat, StrictInt]
    minimum_latency_milliseconds: Union[StrictFloat, StrictInt] = Field(alias="minimumLatencyMilliseconds")
    encryption: Optional[Encryption] = None
    interface: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["streamId", "port", "minimumLatencyMilliseconds", "encryption", "interface"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RistListenerTransportProtocol from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of stream_id
        if self.stream_id:
            _dict['streamId'] = self.stream_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of encryption
        if self.encryption:
            _dict['encryption'] = self.encryption.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RistListenerTransportProtocol from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "streamId": RistStreamIdentifier.from_dict(obj["streamId"]) if obj.get("streamId") is not None else None,
            "port": obj.get("port"),
            "minimumLatencyMilliseconds": obj.get("minimumLatencyMilliseconds") if obj.get("minimumLatencyMilliseconds") is not None else 3000,
            "encryption": Encryption.from_dict(obj["encryption"]) if obj.get("encryption") is not None else None,
            "interface": obj.get("interface")
        })
        return _obj


