# coding: utf-8

"""
    CddService

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.channel_configuration import ChannelConfiguration
from openapi_client.models.id_and_value import IdAndValue
from typing import Optional, Set
from typing_extensions import Self

class RouterDeviceConfiguration(BaseModel):
    """
    RouterDeviceConfiguration
    """ # noqa: E501
    channels: List[ChannelConfiguration]
    simple_settings: Optional[List[IdAndValue]] = Field(default=None, alias="simpleSettings")
    __properties: ClassVar[List[str]] = ["channels", "simpleSettings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RouterDeviceConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in channels (list)
        _items = []
        if self.channels:
            for _item_channels in self.channels:
                if _item_channels:
                    _items.append(_item_channels.to_dict())
            _dict['channels'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in simple_settings (list)
        _items = []
        if self.simple_settings:
            for _item_simple_settings in self.simple_settings:
                if _item_simple_settings:
                    _items.append(_item_simple_settings.to_dict())
            _dict['simpleSettings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RouterDeviceConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "channels": [ChannelConfiguration.from_dict(_item) for _item in obj["channels"]] if obj.get("channels") is not None else None,
            "simpleSettings": [IdAndValue.from_dict(_item) for _item in obj["simpleSettings"]] if obj.get("simpleSettings") is not None else None
        })
        return _obj


